export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const GET_OTHER_PROFILE_REQUEST = 'GET_OTHER_PROFILE_REQUEST';
export const GET_OTHER_PROFILE_SUCCESS = 'GET_OTHER_PROFILE_SUCCESS';
export const GET_OTHER_PROFILE_FAILURE = 'GET_OTHER_PROFILE_FAILURE';
